### ISSUE TITLE
SourceMaps: sourcesContent is null

### ISSUE THREAD

**Issue by cspeer** [carrot/gulp-accord#2]
Hi there,

when I try to create sourcemaps for javascript files as described in the ReadMe, the `sourcesContent` attribute in the generated source map is just `[null]`:

``` javascript
var gulp = require('gulp'),
    sourcemaps = require('gulp-sourcemaps'),
    accord = require('gulp-accord');

gulp.task('default', function(){
  gulp.src('./test.styl')
  .pipe(sourcemaps.init())
  .pipe(accord('minify-js'))
  .pipe(sourcemaps.write('.'))
  .pipe(gulp.dest('./out'))
});
```

Everything works perfect if I skip the minifying part.

Any ideas?

Thanks,
Chris

**Comment by cspeer** [comment]
I just stumbled upon the fact, that if i set:

``` javascript
.pipe(sourcemaps.init({ loadMaps: true }))
```

everything is fine. Not sure why.

**Comment by cspeer** [comment]
Ok, I'm sorry. The problem is https://github.com/Josiah/gulp-cachebust
Please just disregard everything I said before. It's been a long day...
But using cachebuster, even before sourcemaps.init() results in sourcesContent being [null]

**Comment by jescalan** [comment]
💖 glad it was worked out!
